apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: train
spec:
  replicas: 4
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - name: train
        image: gowtham4723/ttrimage:v1
        ports:
        - containerPort: 8080

#-------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata: 
  name: deploy-service
spec:
  type: LoadBalancer
  selector:
    app: train
  ports:
  - port: 80
    targetPort: 8080

