name: CI Pipeline

on:
  push: 
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:

    runs-on: linux
    steps:
      - uses: actions/checkout@v6
      - name: java jdk17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: maven build
        run: echo "SNP@1234567890" | sudo -S apt install -y maven
      - name: clean package
        run: mvn clean package 
      - name: upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: build-artifact
          path: target/*.war
  Image:
    
    runs-on: linux
    needs: build
    steps:
      - uses: actions/checkout@v6
      - name: artifact
        uses: actions/download-artifact@v5
      - name: Docker image
        uses: docker/build-push-action@v6
        with:
          path: target/*.war
          context: .
          push: false
          tags: ttrimage:v1
          file: ./Dockerfile